name: Generate Keystore
on: workflow_dispatch

jobs:
  keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Create keystore
        run: |
          keytool -genkey -v -keystore module.jks -keyalg RSA -keysize 2048 \
            -validity 10000 -alias moduleKey \
            -storepass "MatKhauCuaBan123" -keypass "MatKhauCuaBan123" \
            -dname "CN=Module, OU=Dev, O=Me, L=HCM, S=SG, C=VN"

      - name: Encode to base64 for secrets
        run: base64 -w 0 module.jks > module.jks.b64

      - name: Write info file
        run: |
          echo "KEYSTORE_PASS = MatKhauCuaBan123" > info.txt
          echo "KEY_PASS = MatKhauCuaBan123" >> info.txt
          echo "KEY_ALIAS = moduleKey" >> info.txt

      - uses: actions/upload-artifact@v4
        with:
          name: keystore-output
          path: |
            module.jks.b64
            info.txt